package com.kafka.stream.model;

import java.util.Date;

public class Message {

	private Long sbscr_indv_id;
	private String sbscr_src_sys_id;
	private Date sbscr_eff_dtl_dt;
	private String enrlee_indv_id;
	private Long enrlee_src_sys_id;
	private Date enrlee_eff_dtl_dt;
	private Date mbrshp_eff_dt;
	private String cust_acct_id;
	private Long cust_acct_src_sys_id;
	private Date cust_acct_eff_dtl_dt;
	private String cust_pchs_id;
	private Date cust_pchs_eff_dtl_dt;
	private Date mbrshp_eff_dtl_dt;
	private Long cob_ins_typ_id;
	private Date cob_ins_eff_dt;
	private String cob_ins_carr_nbr;
	private Long cob_cov_typ_id;
	private Date eff_dtl_dt;
	private String creat_user_id;
	private Date creat_tmstmp;
	private String updt_user_id;
	private Date updt_tmstmp;
	private Long aud_id;
	private Date canc_dtl_dt;
	private String medcr_entl_typ_id;
	private Long payr_resp_seq_id;
	private Long cob_rsn_typ_id;
	private String cob_ins_carr_nm;
	private String cob_ins_carr_tax_id;
	private String cob_ins_pol_nbr;
	private String cob_ins_pol_nm;
	private Long custd_typ_id;
	private String cob_ins_tel_nbr;
	private Date cob_ins_verf_dt;
	private Date cob_ins_trm_dt;
	private String cob_ins_ee_id;
	private String cob_ins_ee_2_id;
	private String cob_ins_ee_3_id;
	private String hcfa_nat_pln_id;
	private String cob_note_txt;
	private Integer cob_ins_pst_adr_surrg_key;
	private String adr_ln_1_txt;
	private String adr_ln_2_txt;
	private String adr_ln_3_txt;
	private String adr_ln_4_txt;
	private String adr_ln_5_txt;
	private Integer adr_vld_id;
	private String adr_guid_ver;
	private String res_dlvr_ind;
	private String adr_hse_nbr_wo_frac;
	private String adr_hse_nbr_frac;
	private String adr_str_prfx_dir;
	private String adr_str_nm;
	private String adr_str_sufx_abbr;
	private String adr_str_sufx_dir;
	private String adr_sec_unit_desg;
	private String adr_sec_unit_qual;
	private String adr_po_box_nbr;
	private String adr_rte_desg;
	private String adr_box_nbr;
	private String adr_urbn_nm;
	private String adr_tn_nm;
	private String adr_dlvr_pt_cd;
	private String adr_dlvr_pt_chk_dgt;
	private String adr_carr_rte_cd;
	private String lat_deg;
	private String lng_deg;
	private String pst_cd;
	private String pst_prfx_cd;
	private String pst_sufx_cd;
	private String pst_desc;
	private Long tm_zone_id;
	private String tm_zone_nm;
	private String utc_ofst_tm;
	private Long iso_cntry_id;
	private Long iso_cntry_subdiv_id;
	private Long fips_st_id;
	private Long fips_cnty_id;
	private Long st_prvc_id;
	private String del_in;
	
}
